const animations: { [key: string]: any } = {
    "dips": require('../assets/gym-exercises/dips.json'),
    "skull crushers": require('../assets/gym-exercises/skull-crushers.json'),
    "close grip bench press": require('../assets/gym-exercises/close-grip-bench-press.json'),
    "triceps pushdowns": require('../assets/gym-exercises/triceps-pushdowns.json'),
    "triceps kickbacks": require('../assets/gym-exercises/triceps-kickbacks.json'),
    "overhead triceps extensions": require('../assets/gym-exercises/overhead-triceps-extensions.json'),
    "diamond push-ups": require('../assets/gym-exercises/diamond-push-ups.json'),
    "close grip push-ups": require('../assets/gym-exercises/close-grip-push-ups.json'),
    "bench press": require('../assets/gym-exercises/bench-press.json'),
    "push-ups": require('../assets/gym-exercises/push-ups.json'),
    "chest flyes": require('../assets/gym-exercises/chest-flyes.json'),
    "incline bench press": require('../assets/gym-exercises/incline-bench-press.json'),
    "dumbbell chest press": require('../assets/gym-exercises/dumbbell-chest-press.json'),
    "cable chest press": require('../assets/gym-exercises/cable-chest-press.json'),
    "chest dips": require('../assets/gym-exercises/chest-dips.json'),
    "shoulder press": require('../assets/gym-exercises/shoulder-press.json'),
    "lateral raises": require('../assets/gym-exercises/lateral-raises.json'),
    "arnold press": require('../assets/gym-exercises/arnold-press.json'),
    "front raises": require('../assets/gym-exercises/front-raises.json'),
    "seated dumbbell press": require('../assets/gym-exercises/seated-dumbbell-press.json'),
    "military press": require('../assets/gym-exercises/military-press.json'),
    "upright rows": require('../assets/gym-exercises/upright-rows.json'),
    "rear delt flyes": require('../assets/gym-exercises/rear-delt-flyes.json'),
    "bicep curls": require('../assets/gym-exercises/bicep-curls.json'),
    "hammer curls": require('../assets/gym-exercises/hammer-curls.json'),
    "preacher curls": require('../assets/gym-exercises/preacher-curls.json'),
    "concentration curls": require('../assets/gym-exercises/concentration-curls.json'),
    "preacher hammer curls": require('../assets/gym-exercises/preacher-hammer-curls.json'),
    "spider curls": require('../assets/gym-exercises/spider-curls.json'),
    "zottman curls": require('../assets/gym-exercises/zottman-curls.json'),
    "plank": require('../assets/gym-exercises/plank.json'),
    "russian twists": require('../assets/gym-exercises/russian-twists.json'),
    "bicycle crunches": require('../assets/gym-exercises/bicycle-crunches.json'),
    "mountain climbers": require('../assets/gym-exercises/mountain-climbers.json'),
    "hanging leg raises": require('../assets/gym-exercises/hanging-leg-raises.json'),
    "woodchoppers": require('../assets/gym-exercises/woodchoppers.json'),
    "plank variations": require('../assets/gym-exercises/plank-variations.json'),
    "stability ball crunches": require('../assets/gym-exercises/stability-ball-crunches.json'),
    "deadlifts": require('../assets/gym-exercises/deadlifts.json')
}

export default animations;
